### ISSUE TITLE
Flutter_Locatlization Error 

### ISSUE THREAD

**Issue by kamalaraob** [Albert221/FastShopping#75]
Hello there ,
It seems there is some issue with the localization Package dependencies with the Latest Flutter SDK.. 

**Error :**  

Because fast_shopping depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because fast_shopping depends on intl ^0.16.1, version solving failed.
Running "flutter pub get" in fastshopping...
pub get failed (1; So, because fast_shopping depends on intl ^0.16.1, version solving failed.)

But when I upgrade the intl to 0.17.0,. it is throwing issue related to 

Target dart2js failed: Exception: .../Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.19.1/lib/src/picture_provider.dart:52:59:
Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
.../Flutter/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17:
Info: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
Error: Compilation failed.

**Flutter & Dart Version**

Flutter 2.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 60bd88df91 (2 days ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

**Comment by Albert221** [comment]
This is because you run Fast Shopping with Flutter 2.0.0. Fast Shopping should be compiled using Flutter 1.22.*.
